services:
  cyber-chat:
    build: .  # to build the docker but i need also to run up with build!
    ports:
     - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}