services:
  cyber-chat:
    image: cyberchatwithorm:v3
    build:
      context: .
      target: builder
    command: npm run start:dev
    ports:
     - "3000:3000"
    environment:
      PORT: 3000
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}