import type { Metadata } from "next";
import { Cherry_Bomb_One } from "next/font/google";
import { ThemeProvider } from "./components/ThemeProvider";
import "./globals.css";

const cherryBomb = Cherry_Bomb_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cherry-bomb", // Defines the custom CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={cherryBomb.variable} suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="data-theme"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header style={{ fontFamily: "var(--font-cherry-bomb)" }}>
            <h1>Kiki’s Delivery Service</h1>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
