import type { Metadata } from "next";
import { Cherry_Bomb_One, Geist, Inter, Raleway } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const ralewayHeading = Raleway({subsets:['latin'],variable:'--font-heading'});

const inter = Inter({subsets:['latin'],variable:'--font-sans'});

const cherryBomb = Cherry_Bomb_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-cherry-bomb", // Defines the custom CSS variable
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        
          <header style={{ fontFamily: "var(--font-cherry-bomb)" }}>
            <h1>Kiki’s Delivery Service</h1>
          </header>
          {children}
      </body>
    </html>
  );
}
